"""migracioninicial


Revision ID: 92b630442f05
Revises: 
Create Date: 2025-07-30 15:49:27.483984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b630442f05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Product',
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.Column('productName', sa.String(length=40), nullable=False),
    sa.Column('supplierId', sa.Integer(), nullable=True),
    sa.Column('categoryId', sa.Integer(), nullable=True),
    sa.Column('quantityPerUnit', sa.String(length=20), nullable=True),
    sa.Column('unitPrice', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unitsInStock', sa.SmallInteger(), nullable=True),
    sa.Column('unitsOnOrder', sa.SmallInteger(), nullable=True),
    sa.Column('reorderLevel', sa.SmallInteger(), nullable=True),
    sa.Column('discontinued', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('productId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Product')
    # ### end Alembic commands ###
